version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: riskengine-postgres
    restart: always
    environment:
      POSTGRES_USER: jaspal82@gmail.com
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: riskengine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
